service: sls-sqs-test # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
custom:
  settings:
    ACCOUNT_ID: "031676968139"

provider:
  name: aws
  runtime: nodejs8.10
  provider: juanatrip
  region: ap-southeast-1
  environment: ${self:custom.settings}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:*:MyQueue"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  sqsHello:
    handler: handler.sqsHello
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
